### ISSUE TITLE
Weight parts of sign in comparison

### ISSUE THREAD

**Issue by justopower** [lingpy/pysign#5]
At the moment, we are parsing the following info from transcription:
- symmetry
- initial position (part of location, describing spatial relationship of dominant, nondominant)
- dominant hand
  - shape
  - orientation
  - location
  - contact (properly part of location, but adds extra info)
  - movement
  - repetition (usually part of movement, but it crosses segment boundaries conceptually)
- nondominant
  - shape
  - orientation
  - location
  - contact
  - movement

So in principle all of this can be compared and weighted in different ways.

**Comment by LinguList** [comment]
I added a first proposal. Check the function `Hand.distance`:

https://github.com/lingpy/pysign/blob/9d9744c1f4387572faba119f4a45066a036d8dae/src/pysign/parse.py#L740-L776

The function is open to any kind of similarity you want to use. All you have to do is:

1. decide on a set of weights (if you only want to compare shape, you just pass a dictionary of `{'shape': 1}` and that's it. 
2. decide on a comparison function, so far, I use `identity`, so if the strings are identical: return 0, if they are different, return 1

You can tweak this function in very many ways withouth having to change the library. 

e.g. if you want to test on Jaccard, you first define your jaccard function (there's a `lambda` keyword in python that allows to make functions on the fly):

```python
>>> f = lambda x: x # return x
>>> f('x')
'x'
>>> f = lambda x: x+x # return x+x
>>> f(1)
2
```

So Jaccard is:

```python
>>> jaccard = lambda x, y: len(set(x).intersection(y))/len(set(x).union(set(y))
>>> sign1.dominant.distance(sign2.dominant, compare=jaccard)
```

I suggest you test it, @justopower, and also review my suggestions to compare only dominant hands with each other (which is why it is now useful to have the unintuitive "hand" as an attribute of a sign).

**Comment by justopower** [comment]
I've had a chance to play with the distance function a bit, @LinguList, and everything seems to work like it should. 

`sign1 = Sign.from_text("   ")`
`sign2 = Sign.from_text("   ")`

`sign1.dominant.distance(sign2.dominant, weights={'shape': 1})`
`>>> 1.0 # handshapes are different`

`sign1.dominant.distance(sign2.dominant, compare=jaccard) #using the function you defined above`
`>>> 0.7777777777777778`

The Jaccard measure is a bit funny right now because it includes everything that we parse about a sign, even if it is not *there*; maybe this is in fact what we want, but I need to think about it. 

The above point relates to the output of the parser and what exactly we are comparing. If you look at what the parser returns, in fact what is being compared are lists. I think this means that the lists as a whole will have to be exactly the same for the distance function to measure 0 distance. 

`sign3 = Sign.from_text("    ")`
`sign4 = Sign.from_text("    ")`
`sign3.dominant.shape`
`>>> ['\ue002\ue00d', '\ue002\ue010\ue00d']`
`sign4.dominant.shape`
`>>> ['\ue002\ue00d', '\ue002\ue010']`
`sign3.dominant.distance(sign4.dominant, weights={'shape':1})`
`>>> 1.0`

So it looks like the code works as it should, but we have to think about how the parser's output should be compared, since I think we would rather say that the handshapes in the example above have some similarity that we want to capture. Or am I missing something here between the Sign and Hand classes?

**Comment by LinguList** [comment]
This is so far a yes-no-distance. If they should be further defined, one would  have to defin segment-similarities, or similar, but it is never advisable to make this only based on characters in a string. I also think that Jaccard is not good, but that is also clear. So we should have a discussion about features, salient features, and feature distances. All rather difficult, but let's try to maybe coordinate via email and try to plan something like a blog post, where we could explore this (I started a series on features in https://calc.hypotheses.org but only for sounds, so we could discuss a follow-up for signs, and use this to advance this?)

**Comment by justopower** [comment]
Closing this issue because I think the approach in which we implement current comparison methods is the clearer path forward.
